apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: primeroz/port-scan-exporter
deploy:
  helm:
    releases:
      - name: local
        chartPath: ./charts/port-scan-exporter
        artifactOverrides:
          imageKey: primeroz/port-scan-exporter
          image: primeroz/port-scan-exporter
        imageStrategy:
          fqn: {}
