apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: true
    useDockerCLI: true
    useBuildkit: true
  artifacts:
    - image: docker.io/primeroz/port-scan-exporter
      docker: {}
deploy:
  helm:
    releases:
      - name: local
        chartPath: ./charts/port-scan-exporter
        namespace: monitoring
        setValues: 
          debug: true
        artifactOverrides:
          imageKey: docker.io/primeroz/port-scan-exporter
          image: docker.io/primeroz/port-scan-exporter
        imageStrategy:
          fqn: {}
