apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
  name: {{ include "port-scan-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "port-scan-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "port-scan-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
