apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
  name: {{ include "port-scan-exporter.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "port-scan-exporter.serviceAccountName" . }}
  verbs:
  - use
